version: '3'
services:
  web:  
    build: ./web
    network_mode: "host"
  postgres:
    build: ./db
    restart: always
    network_mode: "host"
    volumes:
      - db-data:/var/lib/postgresql/data
    
volumes:
  db-data:
    driver: local